created values page with checkboxes completed for values
Girl-Squad-Essentialism/front-end pull request #7
Opened 2021-06-11 16:48 UTC by DanielleKoduru

2021-06-29 17:20 UTC, clarejackson approved these changes
This looks great! Your code will help me get going on the projects feature, thank you.

2021-06-29 21:30 UTC, jduell12 requested changes

2021-06-29 21:30 UTC, jduell12 commented on src/App.js
> +      </Route>
Could we indent here for easier reading? So the Routes will be indented and the Switch tag will stay where it is

2021-06-29 21:30 UTC, jduell12 commented on src/components/values/ValuesPrompt.js
> +    }
I know this isn't complete yet but you also want to save the value to the appropriate state value

2021-06-29 21:30 UTC, jduell12 commented on src/components/values/values.js
> +        history.push("/valuesprompt")
Also make sure to change state back to the initial state (aka empty)

2021-06-29 21:30 UTC, jduell12 commented on src/components/values/values.js
> +                    <div className="values-column">
Since this div is repeated and just changed based on the name in the Values array. You could create this div as another component and loop through your values and pass the value name to the component and then return all of this. 

It will have the same outcome but if you end up modifying the values list in the future having it as a component will mean you don't have to change anything in this return statement

2021-06-29 21:49 UTC, DanielleKoduru commented on src/App.js
> +      </Route>
Yes. I can definitely indent. Thanks for catching this.

2021-06-29 21:57 UTC, DanielleKoduru commented on src/components/values/ValuesPrompt.js
> +    }
I commented your suggestions here regarding state management and making sure we save the value to the appropriate state value.

2021-06-29 21:58 UTC, DanielleKoduru commented on src/components/values/values.js
> +        history.push("/valuesprompt")
I commented in a .finally to have here for when we want to change state back to initial state

2021-06-30 16:00 UTC, jduell12 approved these changes

2021-06-30 16:01 UTC, merged